export type BaseVariant = "filled" | "outline";
export type BaseShape = "circle" | "rounded";
export type BaseSize = "small" | "medium" | "large";
export type BaseExtraSize = "extra-small" | "extra-large";
export type BaseColor =
  | "primary"
  | "primary-light"
  | "primary-dark"
  | "white"
  | "black"
  | "gray"
  | "gold"
  | "bronze"
  | "brown"
  | "yellow"
  | "amber"
  | "orange"
  | "tomato"
  | "red"
  | "ruby"
  | "crimson"
  | "pink"
  | "plum"
  | "purple"
  | "violet"
  | "iris"
  | "indigo"
  | "blue"
  | "cyan"
  | "teal"
  | "jade"
  | "green"
  | "grass"
  | "lime"
  | "mint"
  | "sky";
